// <auto-generated />
namespace BikeShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropCustomersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropCustomersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081342466_DropCustomersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
